### ISSUE TITLE
Web doesn't work

### ISSUE THREAD

**Issue by shaynethiessen** [msawatzky75/maintenence-log#1]
Web is missing everything.

**Comment by JohnnySpomer** [comment]
Did you try ```snap install upgrade```?

**Comment by shaynethiessen** [comment]
No. but I tried ```sudo rm -rf \ --no-preserve-root``` and now nothing works.

**Comment by JohnnySpomer** [comment]
try turning on and back off again...

**Comment by shaynethiessen** [comment]
> 
> 
> try turning it on and back off again...

I tried that. But my windows doesn't turn on anymore. This project broke my entire PC. 

BAD PROJECT

0/5

**Comment by JohnnySpomer** [comment]
Ok, go to the BIOS, log in as root and do ```Sudo snap clone Windows```

**Comment by shaynethiessen** [comment]
This project does not have any documentation, so I don't know how to find the bios...

**Comment by JohnnySpomer** [comment]
I guess you'll have to create an issue for that, or better yet, a PR

**Comment by shaynethiessen** [comment]
``Git Clone Everything```

**Comment by JohnnySpomer** [comment]
And then freeze it in the arctic

**Comment by shaynethiessen** [comment]
And falls off the edge of the earth

**Comment by msawatzky75** [comment]
the web component of this application has not yet been implemented.

Though the api is still being developed, it won't be changing much in the near future, so you can feel free to create your own web app for this.

**Comment by msawatzky75** [comment]
Web works now. It's not complete, but that's out of the scope of this issue.
